[package]
name = "ser_parser"
version = "0.1.0"
authors = ["Jan-Willem Buurlage"]

[lib]
name = "ser_parser"
crate-type = ["cdylib", "lib"]

[dependencies]
nom = ">=0.4.1"
hex = ">= 0.3.0"
image = ">= 0.20"

[dependencies.pyo3]
version = "0.4"
features = ["extension-module"]
