[package]
name = "ser_parser"
version = "0.1.0"
authors = ["Jan-Willem Buurlage"]

[lib]
name = "ser_parser"
crate-type = ["cdylib", "lib"]

[dependencies]
nom = "^4"
hex = ">= 0.3.0"
image = "<= 0.23.3"
cpython = { version = "0.2.1", features = ["extension-module"]}
